//! Transpile Jolt verifier stages 1-7 (all sumchecks) to circuit code for various proving backends.
//!
//! # Overview
//!
//! This binary performs symbolic execution of the Jolt verifier to generate circuit code.
//! Instead of computing with actual field elements, we use `MleAst`, a symbolic type that
//! records all arithmetic operations as an AST (Abstract Syntax Tree). This AST is then
//! converted to target-specific code (e.g., Go for gnark).
//!
//! # Supported Targets
//!
//! - **gnark** (default): Go/Groth16 circuit generation
//! - **ast-bundle**: Output only the AstBundle JSON (no code generation)
//!
//! # Scope: Stages 1-7 (All Sumcheck Verification)
//!
//! This transpiler covers stages 1-7, which verify all sumcheck proofs:
//! - Stages 1-6: Standard sumcheck verifications
//! - Stage 7: HammingWeight claim reduction sumcheck
//!
//! Stage 8 (PCS/Hyrax verification) is NOT transpiled because:
//! - **Hyrax requires native curve operations**: MSM on Grumpkin must use native implementations.
//! - **Native implementation needed**: PCS verification must be implemented directly in the
//!   target framework using native curve operations.
//!
//! Note: Stage 7 does not include AdviceClaimReduction verifiers (they require state management
//! across stages 6-7). For proofs without advice, this is complete.
//!
//! # Pipeline
//!
//! 1. Load proof, io_device, and preprocessing from files (generated by jolt-sdk)
//! 2. Convert proof values to symbolic variables (`MleAst`) with `symbolize_proof`
//! 3. Run the verifier with symbolic types: this records all operations to the AST
//! 4. Collect equality assertions (the verifier's `assert_eq!` calls become circuit constraints)
//! 5. Build AstBundle (target-agnostic intermediate representation)
//! 6. Generate target-specific circuit code from the AST
//! 7. Output witness values (captured during symbolization)

use ark_serialize::CanonicalDeserialize;
use clap::{Parser, ValueEnum};
use std::collections::HashMap;
use std::path::PathBuf;

use common::jolt_device::JoltDevice;
use jolt_core::poly::commitment::dory::DoryCommitmentScheme;
use jolt_core::transcripts::Transcript;
use jolt_core::zkvm::ram::{set_pending_initial_ram, set_pending_io_mle, PendingInitialRamValues, PendingIoMleValues};
use jolt_core::zkvm::transpilable_verifier::TranspilableVerifier;
use jolt_core::zkvm::verifier::JoltVerifierPreprocessing;
use jolt_core::zkvm::RV64IMACProof;
use transpiler::{
    gnark_codegen, symbolize_proof, AstCommitmentScheme, AstOpeningAccumulator,
    SelectedAstTranscript,
};
use zklean_extractor::mle_ast::{
    enable_constraint_mode, take_constraints as take_assertions, AstBundle, MleAst, TargetField,
    WitnessType,
};

// Output file names (bundle is target-agnostic)
const BUNDLE_FILENAME: &str = "stages_bundle.json";

/// Transpilation target backends.
#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub enum TranspilationTarget {
    /// Go/gnark circuit for Groth16 proving
    #[default]
    Gnark,
    /// Output only the AstBundle (no code generation)
    AstBundle,
}

/// Transpile Jolt proofs to circuit code for various proving backends.
///
/// Takes a Jolt proof, io_device, and preprocessing files as input,
/// and generates circuit code and witness data for the specified target.
#[derive(Parser)]
#[command(name = "transpiler")]
#[command(version, about)]
struct Args {
    /// Path to the proof file (serialized JoltProof)
    #[arg(long, default_value = "/tmp/fib_proof.bin")]
    proof: PathBuf,

    /// Path to the io_device file (inputs/outputs)
    #[arg(long, default_value = "/tmp/fib_io_device.bin")]
    io_device: PathBuf,

    /// Path to the preprocessing file
    #[arg(long, default_value = "/tmp/jolt_verifier_preprocessing.dat")]
    preprocessing: PathBuf,

    /// Transpilation target language/framework
    #[arg(long, short = 't', default_value = "gnark", value_enum)]
    target: TranspilationTarget,

    /// Output directory (defaults to target-specific directory, e.g., "go" for gnark)
    #[arg(long, short = 'o')]
    output_dir: Option<PathBuf>,
}

/// Symbolize IO device data for universal circuit generation.
///
/// Allocates symbolic variables for inputs, outputs, and panic, then pushes
/// override values to thread-locals consumed during `verify()`:
///
/// 1. **Preamble overrides** (`PENDING_BYTES_OVERRIDES`): Elements for Poseidon hashing
///    in `fiat_shamir_preamble`. Padded to max_input_size/max_output_size.
///
/// 2. **eval_io_mle overrides** (`PENDING_IO_MLE`): u64-word field elements for
///    `eval_io_mle_symbolic`. Padded to max_input_size/8 and max_output_size/8 words.
///
/// 3. **eval_initial_ram_mle overrides** (`PENDING_INITIAL_RAM`): Input words for
///    the initial RAM evaluation (same variables as point 2).
///
/// All IO is padded to max sizes from MemoryLayout so the circuit structure is
/// fixed regardless of actual IO size. `fiat_shamir_preamble` applies the same
/// padding on the prover side.
fn symbolize_io_device(
    io_device: &JoltDevice,
    var_alloc: &mut transpiler::symbolic_proof::VarAllocator,
) -> Vec<MleAst> {
    use ark_ff::PrimeField;
    use transpiler::symbolic_traits::io_replay::push_bytes_override;

    let max_input = io_device.memory_layout.max_input_size as usize;
    let max_output = io_device.memory_layout.max_output_size as usize;

    // Pad inputs and outputs to max sizes (matches fiat_shamir_preamble padding).
    let mut padded_inputs = io_device.inputs.clone();
    padded_inputs.resize(max_input, 0);
    let mut padded_outputs = io_device.outputs.clone();
    padded_outputs.resize(max_output, 0);

    // --- 1. Preamble overrides (32-byte chunk scalars) ---
    // These match what raw_append_bytes produces: bytes → 32-byte padded → Fr scalar.
    let preamble_input_elements: Vec<MleAst> = padded_inputs
        .chunks(32)
        .enumerate()
        .map(|(i, chunk)| {
            let mut buf = [0u8; 32];
            buf[..chunk.len()].copy_from_slice(chunk);
            let concrete = ark_bn254::Fr::from_le_bytes_mod_order(&buf);
            var_alloc.alloc_with_value(&format!("io_preamble_input_{i}"), &concrete)
        })
        .collect();

    let preamble_output_elements: Vec<MleAst> = padded_outputs
        .chunks(32)
        .enumerate()
        .map(|(i, chunk)| {
            let mut buf = [0u8; 32];
            buf[..chunk.len()].copy_from_slice(chunk);
            let concrete = ark_bn254::Fr::from_le_bytes_mod_order(&buf);
            var_alloc.alloc_with_value(&format!("io_preamble_output_{i}"), &concrete)
        })
        .collect();

    // Panic → 8 bytes → 32-byte padded → Fr scalar → symbolic var
    let panic_u64 = io_device.panic as u64;
    let mut panic_padded = [0u8; 32];
    panic_padded[..8].copy_from_slice(&panic_u64.to_le_bytes());
    let panic_concrete = ark_bn254::Fr::from_le_bytes_mod_order(&panic_padded);
    let preamble_panic_element =
        var_alloc.alloc_with_value("io_preamble_panic", &panic_concrete);

    // Push in the exact order fiat_shamir_preamble calls append_bytes:
    // 1. inputs, 2. outputs, 3. panic
    push_bytes_override(preamble_input_elements);
    push_bytes_override(preamble_output_elements);
    push_bytes_override(vec![preamble_panic_element]);

    // --- 2. eval_io_mle overrides (u64-word field elements, padded to max) ---
    let num_input_words = max_input / 8;
    let num_output_words = max_output / 8;

    let eval_input_words: Vec<MleAst> = padded_inputs
        .chunks(8)
        .enumerate()
        .take(num_input_words)
        .map(|(i, chunk)| {
            let val = u64::from_le_bytes(chunk.try_into().unwrap());
            let concrete = ark_bn254::Fr::from(val);
            var_alloc.alloc_with_value(&format!("io_eval_input_{i}"), &concrete)
        })
        .collect();

    let eval_output_words: Vec<MleAst> = padded_outputs
        .chunks(8)
        .enumerate()
        .take(num_output_words)
        .map(|(i, chunk)| {
            let val = u64::from_le_bytes(chunk.try_into().unwrap());
            let concrete = ark_bn254::Fr::from(val);
            var_alloc.alloc_with_value(&format!("io_eval_output_{i}"), &concrete)
        })
        .collect();

    let eval_panic_val = {
        let concrete = ark_bn254::Fr::from(io_device.panic as u64);
        var_alloc.alloc_with_value("io_eval_panic", &concrete)
    };

    // Set pending IO MLE values (consumed by eval_io_mle)
    set_pending_io_mle(PendingIoMleValues {
        input_words: eval_input_words.clone(),
        output_words: eval_output_words,
        panic_val: eval_panic_val,
    });

    // NOTE: PENDING_INITIAL_RAM is set in main() after symbolize_bytecode()
    // provides the bytecode_words. eval_input_words are returned for that purpose.

    println!(
        "  Preamble: {} input chunks + {} output chunks + 1 panic",
        max_input / 32,
        max_output / 32,
    );
    println!(
        "  Eval: {} input words + {} output words + 1 panic",
        num_input_words, num_output_words,
    );

    eval_input_words
}

/// Tracks which variable indices need witness fixup after symbolic verification.
struct BytecodeFixupIndices {
    /// Variable indices for eq_r_register_4: [rd_eq4, rs1_eq4, rs2_eq4]
    eq_r4_var_indices: [u32; 3],
    /// Variable index for eq_r_register_5_rd
    eq_r5_rd_var_index: u32,
    /// Variable index for stage5_lookup_contribution
    lookup_contribution_var_index: u32,
}

/// Data returned by symbolize_bytecode for witness fixup after verify().
struct BytecodeSymbolizationData {
    /// Symbolic bytecode words for PENDING_INITIAL_RAM.
    bytecode_words: Vec<MleAst>,
    /// Concrete register indices per instruction (rd, rs1, rs2).
    register_indices: Vec<(Option<u8>, Option<u8>, Option<u8>)>,
    /// Concrete lookup table index per instruction (None if no lookup table).
    lookup_table_indices: Vec<Option<usize>>,
    /// Variable indices for challenge-dependent fields that need fixup.
    fixup_indices: Vec<BytecodeFixupIndices>,
}

/// Symbolize bytecode data for universal circuit generation (cross-program universality).
///
/// Allocates symbolic variables for:
/// 1. **bytecode_words** — RAM initialization values (for eval_initial_ram_mle)
/// 2. **instruction fields** — address, imm, flags, register eq lookups, lookup contribution
///    (for compute_val_polys). Challenge-dependent fields get placeholder (zero) witness values
///    that are fixed up after symbolic verification via `fixup_bytecode_witnesses()`.
///
/// Sets PENDING_BYTECODE_INSTRUCTIONS thread-local for compute_val_polys.
fn symbolize_bytecode(
    preprocessing: &JoltVerifierPreprocessing<ark_bn254::Fr, DoryCommitmentScheme>,
    var_alloc: &mut transpiler::symbolic_proof::VarAllocator,
) -> BytecodeSymbolizationData {
    use jolt_core::field::JoltField;
    use jolt_core::zkvm::bytecode::read_raf_checking::{
        set_pending_bytecode_instructions, PendingBytecodeInstructions, SymbolicInstruction,
    };
    use jolt_core::zkvm::instruction::{
        Flags, InstructionLookup, InterleavedBitsMarker, NUM_CIRCUIT_FLAGS, NUM_INSTRUCTION_FLAGS,
    };
    use jolt_core::zkvm::lookup_table::LookupTables;
    use std::array;

    let bytecode = &preprocessing.shared.bytecode.bytecode;
    let bytecode_words = &preprocessing.shared.ram.bytecode_words;

    // 1. Bytecode words for eval_initial_ram_mle
    let sym_bytecode_words: Vec<MleAst> = bytecode_words
        .iter()
        .enumerate()
        .map(|(i, &w)| {
            let concrete = ark_bn254::Fr::from(w);
            var_alloc.alloc_with_value(&format!("bc_word_{i}"), &concrete)
        })
        .collect();

    // 2. Instruction fields for compute_val_polys
    let mut sym_instructions = Vec::with_capacity(bytecode.len());
    let mut register_indices = Vec::with_capacity(bytecode.len());
    let mut lookup_table_indices = Vec::with_capacity(bytecode.len());
    let mut fixup_indices = Vec::with_capacity(bytecode.len());

    for (k, instruction) in bytecode.iter().enumerate() {
        let instr = instruction.normalize();
        let cf = instruction.circuit_flags();
        let inf = instruction.instruction_flags();

        // Concrete fields (known at symbolization time)
        let address = var_alloc.alloc_with_value(
            &format!("bc_{k}_addr"),
            &ark_bn254::Fr::from(instr.address as u64),
        );
        let imm = var_alloc.alloc_with_value(
            &format!("bc_{k}_imm"),
            &ark_bn254::Fr::from_i128(instr.operands.imm),
        );
        let circuit_flags: [MleAst; NUM_CIRCUIT_FLAGS] = array::from_fn(|i| {
            var_alloc.alloc_with_value(
                &format!("bc_{k}_cf{i}"),
                &ark_bn254::Fr::from(cf[i] as u64),
            )
        });
        let instruction_flags: [MleAst; NUM_INSTRUCTION_FLAGS] = array::from_fn(|i| {
            var_alloc.alloc_with_value(
                &format!("bc_{k}_if{i}"),
                &ark_bn254::Fr::from(inf[i] as u64),
            )
        });
        let stage5_not_interleaved = var_alloc.alloc_with_value(
            &format!("bc_{k}_not_intl"),
            &ark_bn254::Fr::from(!cf.is_interleaved_operands() as u64),
        );

        // Challenge-dependent fields → placeholder zeros (fixed up after verify)
        let eq_r4_start = var_alloc.next_idx();
        let eq_r_register_4: [MleAst; 3] = {
            let names = ["rd", "rs1", "rs2"];
            array::from_fn(|i| {
                var_alloc.alloc_with_value(
                    &format!("bc_{k}_{}_eq4", names[i]),
                    &ark_bn254::Fr::from(0u64),
                )
            })
        };
        let eq5_idx = var_alloc.next_idx();
        let eq_r_register_5_rd = var_alloc.alloc_with_value(
            &format!("bc_{k}_rd_eq5"),
            &ark_bn254::Fr::from(0u64),
        );
        let lut_idx = var_alloc.next_idx();
        let stage5_lookup_contribution = var_alloc.alloc_with_value(
            &format!("bc_{k}_lut"),
            &ark_bn254::Fr::from(0u64),
        );

        fixup_indices.push(BytecodeFixupIndices {
            eq_r4_var_indices: [eq_r4_start, eq_r4_start + 1, eq_r4_start + 2],
            eq_r5_rd_var_index: eq5_idx,
            lookup_contribution_var_index: lut_idx,
        });

        sym_instructions.push(SymbolicInstruction {
            address,
            imm,
            circuit_flags,
            instruction_flags,
            eq_r_register_4,
            eq_r_register_5_rd,
            stage5_not_interleaved,
            stage5_lookup_contribution,
        });

        register_indices.push((instr.operands.rd, instr.operands.rs1, instr.operands.rs2));
        lookup_table_indices.push(
            instruction
                .lookup_table()
                .map(|t| LookupTables::<{ common::constants::XLEN }>::enum_index(&t)),
        );
    }

    // Set thread-local for compute_val_polys
    set_pending_bytecode_instructions(PendingBytecodeInstructions {
        instructions: sym_instructions,
        register_indices: register_indices.clone(),
        lookup_table_indices: lookup_table_indices.clone(),
    });

    println!(
        "  Bytecode words: {}, Instructions: {}",
        bytecode_words.len(),
        bytecode.len(),
    );
    println!(
        "  Variables per instruction: {} concrete + 5 challenge-dependent",
        2 + NUM_CIRCUIT_FLAGS + NUM_INSTRUCTION_FLAGS + 1, // addr + imm + cf + if + not_intl
    );

    BytecodeSymbolizationData {
        bytecode_words: sym_bytecode_words,
        register_indices,
        lookup_table_indices,
        fixup_indices,
    }
}

/// Fix up challenge-dependent witness values in bytecode symbolization.
///
/// After symbolic verification, CapturedBytecodeData contains the concrete eq_r_register
/// tables and stage5_gammas as MleAst expressions. We evaluate these to Fr and use them
/// to compute the correct witness values for each instruction's placeholder fields.
fn fixup_bytecode_witnesses(
    bytecode_data: &BytecodeSymbolizationData,
    var_alloc: &mut transpiler::symbolic_proof::VarAllocator,
) {
    use jolt_core::zkvm::bytecode::read_raf_checking::{
        take_captured_bytecode_data, CapturedBytecodeData,
    };
    use std::collections::HashMap;
    use transpiler::evaluate_concrete::evaluate_concrete;

    let captured: CapturedBytecodeData<MleAst> = take_captured_bytecode_data()
        .expect("CapturedBytecodeData not set — verify() may not have reached stage 6");

    // Evaluate the symbolic eq_r_register tables and gammas to concrete Fr.
    let var_values = var_alloc.concrete_values();
    let mut cache = HashMap::new();

    let eq_r4_table: Vec<ark_bn254::Fr> = captured
        .eq_r_register_4
        .iter()
        .map(|ast| evaluate_concrete(ast, var_values, &mut cache))
        .collect();
    let eq_r5_table: Vec<ark_bn254::Fr> = captured
        .eq_r_register_5
        .iter()
        .map(|ast| evaluate_concrete(ast, var_values, &mut cache))
        .collect();
    let stage5_gammas: Vec<ark_bn254::Fr> = captured
        .stage5_gammas
        .iter()
        .map(|ast| evaluate_concrete(ast, var_values, &mut cache))
        .collect();

    println!("\n=== Fixing Up Bytecode Witnesses ===");
    println!(
        "  eq_r_register_4 table: {} entries",
        eq_r4_table.len()
    );
    println!(
        "  eq_r_register_5 table: {} entries",
        eq_r5_table.len()
    );
    println!(
        "  stage5_gammas: {} entries",
        stage5_gammas.len()
    );

    // Fix up each instruction's placeholder witness values.
    let mut fixed_count = 0;
    for (k, fixup) in bytecode_data.fixup_indices.iter().enumerate() {
        let (rd, rs1, rs2) = bytecode_data.register_indices[k];
        let table_idx = bytecode_data.lookup_table_indices[k];

        // eq_r_register_4: [rd_eq4, rs1_eq4, rs2_eq4]
        let rd_eq4 = rd.map_or(ark_bn254::Fr::from(0u64), |r| eq_r4_table[r as usize]);
        let rs1_eq4 = rs1.map_or(ark_bn254::Fr::from(0u64), |r| eq_r4_table[r as usize]);
        let rs2_eq4 = rs2.map_or(ark_bn254::Fr::from(0u64), |r| eq_r4_table[r as usize]);
        var_alloc.update_witness(fixup.eq_r4_var_indices[0], &rd_eq4);
        var_alloc.update_witness(fixup.eq_r4_var_indices[1], &rs1_eq4);
        var_alloc.update_witness(fixup.eq_r4_var_indices[2], &rs2_eq4);

        // eq_r_register_5_rd
        let rd_eq5 = rd.map_or(ark_bn254::Fr::from(0u64), |r| eq_r5_table[r as usize]);
        var_alloc.update_witness(fixup.eq_r5_rd_var_index, &rd_eq5);

        // stage5_lookup_contribution
        let lut_val = table_idx.map_or(ark_bn254::Fr::from(0u64), |idx| stage5_gammas[2 + idx]);
        var_alloc.update_witness(fixup.lookup_contribution_var_index, &lut_val);

        fixed_count += 5;
    }
    println!("  Fixed {} witness values", fixed_count);
}

fn main() {
    let args = Args::parse();

    println!(
        "=== Transpiling Jolt Verifier Stages 1-7 to {:?} ===\n",
        args.target
    );

    // =========================================================================
    // Step 1: Load input files
    // =========================================================================
    // These files are generated by running a Jolt program with --save flag:
    //   cargo run -p fibonacci --features transcript-poseidon -- --save 50
    //
    // - proof: The JoltProof containing commitments, sumcheck polynomials, etc.
    // - io_device: Program inputs/outputs (needed for transcript initialization)
    // - preprocessing: Verifier setup data (bytecode commitments, memory layout)

    println!("Loading proof from: {:?}", args.proof);
    let proof_bytes = std::fs::read(&args.proof)
        .unwrap_or_else(|e| panic!("Failed to read proof file {:?}: {}", args.proof, e));
    let real_proof: RV64IMACProof = CanonicalDeserialize::deserialize_compressed(&proof_bytes[..])
        .expect("Failed to deserialize proof");
    println!("  trace_length: {}", real_proof.trace_length);
    println!("  commitments: {}", real_proof.commitments.len());

    println!("\nLoading io_device from: {:?}", args.io_device);
    let io_device_bytes = std::fs::read(&args.io_device)
        .unwrap_or_else(|e| panic!("Failed to read io_device file {:?}: {}", args.io_device, e));
    let io_device: JoltDevice = CanonicalDeserialize::deserialize_compressed(&io_device_bytes[..])
        .expect("Failed to deserialize io_device");
    println!("  inputs: {} bytes", io_device.inputs.len());
    println!("  outputs: {} bytes", io_device.outputs.len());

    // Preprocessing uses DoryCommitmentScheme, the default PCS in jolt-sdk.
    // We only need the `shared` field (memory layout, bytecode info) for transpilation;
    // the commitment scheme generators are replaced with stubs for symbolic execution.
    println!("\nLoading preprocessing from: {:?}", args.preprocessing);
    let preprocessing_bytes = std::fs::read(&args.preprocessing).unwrap_or_else(|e| {
        panic!(
            "Failed to read preprocessing file {:?}: {}",
            args.preprocessing, e
        )
    });
    let real_preprocessing: JoltVerifierPreprocessing<ark_bn254::Fr, DoryCommitmentScheme> =
        CanonicalDeserialize::deserialize_compressed(&preprocessing_bytes[..])
            .expect("Failed to deserialize preprocessing");
    println!(
        "  memory_layout: {:?}",
        real_preprocessing.shared.memory_layout
    );

    // Convert to symbolic preprocessing: replace Dory generators with AstVerifierSetup stub.
    // The `shared` field (memory layout, bytecode info) is reused as-is.
    // AstCommitmentScheme satisfies the CommitmentScheme trait but performs no cryptographic
    // operations. PCS verification is skipped in stages 1-6.
    let symbolic_preprocessing: JoltVerifierPreprocessing<MleAst, AstCommitmentScheme> =
        JoltVerifierPreprocessing {
            generators: transpiler::symbolic_traits::ast_commitment_scheme::AstVerifierSetup,
            shared: real_preprocessing.shared.clone(),
        };

    // =========================================================================
    // Step 2: Convert proof to symbolic representation
    // =========================================================================
    // symbolize_proof() converts each proof field (commitments, sumcheck polynomials,
    // opening proofs) into MleAst symbolic variables. Each variable gets a unique ID
    // and descriptive name (e.g., "Stage1_Sumcheck_R0_0" for round 0, coefficient 0).
    //
    // Returns:
    // - symbolic_proof: JoltProof<MleAst> with symbolic variables instead of Fr values
    // - accumulator: AstOpeningAccumulator to collect polynomial opening claims
    // - var_alloc: Tracks variable IDs and names for witness generation
    println!("\n=== Symbolizing Proof ===");
    let (symbolic_proof, accumulator, mut var_alloc) =
        symbolize_proof::<SelectedAstTranscript>(&real_proof);
    println!("  Total symbolic variables: {}", var_alloc.next_idx());

    // =========================================================================
    // Step 2b: Symbolize IO device for universal circuit
    // =========================================================================
    // For universal circuits, IO data (inputs, outputs, panic) must be witness
    // variables instead of constants. This ensures the circuit is identical
    // regardless of the actual inputs/outputs.
    println!("\n=== Symbolizing IO Device ===");
    let eval_input_words = symbolize_io_device(&io_device, &mut var_alloc);
    println!("  Total symbolic variables after IO: {}", var_alloc.next_idx());

    // =========================================================================
    // Step 2c: Symbolize bytecode for universal circuit (cross-program)
    // =========================================================================
    println!("\n=== Symbolizing Bytecode ===");
    let bytecode_data = symbolize_bytecode(&real_preprocessing, &mut var_alloc);
    println!("  Total symbolic variables after bytecode: {}", var_alloc.next_idx());

    // Set PENDING_INITIAL_RAM with both bytecode_words and input_words
    set_pending_initial_ram(PendingInitialRamValues {
        bytecode_words: bytecode_data.bytecode_words.clone(),
        input_words: eval_input_words,
    });

    // Create transcript for Fiat-Shamir challenges.
    // IMPORTANT: The proof must have been generated with the same transcript feature,
    // otherwise challenge values will mismatch and verification will fail.
    let transcript: SelectedAstTranscript = Transcript::new(b"Jolt");

    // =========================================================================
    // Step 3: Set up symbolic verifier
    // =========================================================================
    // TranspilableVerifier is the same as the normal Jolt verifier, but parameterized
    // with symbolic types (MleAst, AstCommitmentScheme, etc.) instead of concrete ones.
    // When verify() is called (Step 4), it executes the verification logic but records
    // all arithmetic operations to the AST instead of computing actual results.
    println!("\n=== Creating TranspilableVerifier ===");
    let verifier = TranspilableVerifier::<
        MleAst,
        AstCommitmentScheme,
        SelectedAstTranscript,
        AstOpeningAccumulator,
    >::new_with_accumulator(
        &symbolic_preprocessing,
        symbolic_proof,
        io_device,
        None, // trusted_advice_commitment (not used in stages 1-6)
        transcript,
        accumulator,
    );

    // =========================================================================
    // Step 4: Run symbolic verification
    // =========================================================================
    // Enable constraint mode so that equality comparisons (==) on MleAst values
    // register as constraints instead of returning bool. This captures the verifier's
    // assert_eq! calls as circuit constraints.
    enable_constraint_mode();

    // Execute verification stages 1-6. This performs symbolic execution:
    // - All field arithmetic (add, mul, sub, inv) builds up the AST
    // - Poseidon hashes for Fiat-Shamir challenges are computed symbolically
    // - Equality assertions are recorded as constraints
    //
    // Stages 1-7 cover all sumcheck verifications. Stage 8 (PCS/Hyrax verification)
    // is not transpiled, it requires native curve operations in Gnark.
    println!("\n=== Running Symbolic Verification (Stages 1-7) ===");
    match verifier.verify() {
        Ok(()) => println!("  Verification completed successfully"),
        Err(e) => {
            println!("  Verification error: {e:?}");
            return;
        }
    }

    // =========================================================================
    // Step 4b: Fix up bytecode witness values
    // =========================================================================
    // During symbolic verification, compute_val_polys captured the concrete
    // eq_r_register tables and stage5_gammas (CapturedBytecodeData). These are
    // MleAst expressions that we now evaluate to concrete Fr to fix up the
    // placeholder (zero) witness values for challenge-dependent instruction fields.
    fixup_bytecode_witnesses(&bytecode_data, &mut var_alloc);

    // Collect the assertions that were registered during verification.
    // Each assertion is an equality check: (lhs == rhs) becomes (lhs - rhs == 0).
    // These become api.AssertIsEqual(lhs, rhs) calls in the Gnark circuit.
    let assertions = take_assertions();
    println!("\n=== Accumulated Assertions ===");
    println!("  Total assertions: {}", assertions.len());

    // =========================================================================
    // Step 5: Build AstBundle for code generation
    // =========================================================================
    // AstBundle is the intermediate representation that bridges symbolic execution
    // and code generation. It contains:
    // - inputs: All symbolic variables (proof data that becomes circuit witness)
    // - constraints: Equality assertions that the circuit must enforce
    // - arena snapshot: The AST nodes representing all computed expressions
    println!("\n=== Building AstBundle ===");
    let mut bundle = AstBundle::new();
    bundle.snapshot_arena();

    // Register all symbolic variables as circuit inputs (witness values).
    // These will become struct fields in the generated Gnark circuit.
    // Use descriptions_with_fields() to include target field metadata.
    for (idx, name, target_field) in var_alloc.descriptions_with_fields() {
        bundle.add_input_with_field(*idx, name.clone(), WitnessType::ProofData, *target_field);
    }

    // Early warning if non-native field arithmetic is needed (not yet implemented)
    if bundle.has_inputs_for_field(TargetField::Fq) {
        let fr_count = bundle.count_inputs_for_field(TargetField::Fr);
        let fq_count = bundle.count_inputs_for_field(TargetField::Fq);
        eprintln!(
            "⚠️  Bundle contains {} non-native field variables (and {} native Fr variables).",
            fq_count, fr_count
        );
        eprintln!("    Non-native field codegen is not yet implemented. Codegen will panic.");
    }
    println!("  Inputs: {}", bundle.inputs.len());

    // Register all equality assertions as circuit constraints.
    // Each assertion (lhs == rhs) becomes api.AssertIsEqual(lhs, rhs) in Gnark.
    for (i, assertion) in assertions.iter().enumerate() {
        bundle.add_constraint_eq_zero(format!("assertion_{i}"), assertion.root());
    }
    println!("  Constraints: {}", bundle.constraints.len());

    // Run CSE (Common Subexpression Elimination) at the AST level.
    // This pre-computes which nodes should be hoisted to named variables,
    // making codegen simpler (just reads pre-computed decisions).
    bundle.run_cse();
    println!(
        "  CSE bindings: {} total across {} constraints",
        bundle.constraint_cse.iter().map(|c| c.bindings.len()).sum::<usize>(),
        bundle.constraint_cse.len()
    );

    // =========================================================================
    // Step 6: Resolve output directory and write bundle
    // =========================================================================
    let default_output_dir = match args.target {
        TranspilationTarget::Gnark => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("go"),
        TranspilationTarget::AstBundle => PathBuf::from("."),
    };
    let output_dir = args.output_dir.clone().unwrap_or(default_output_dir);

    // Save bundle to JSON (common to all targets)
    let bundle_path = output_dir.join(BUNDLE_FILENAME);
    bundle
        .write_json(&bundle_path)
        .unwrap_or_else(|e| panic!("Failed to write bundle file {bundle_path:?}: {e}"));
    println!("  Bundle written to: {bundle_path:?}");

    // =========================================================================
    // Step 7: Target-specific code generation
    // =========================================================================
    match args.target {
        TranspilationTarget::Gnark => {
            // Generate gnark circuit
            // generate_circuit_from_bundle() traverses the AST and emits Go code:
            // - Each AST node (Add, Mul, Sub, etc.) becomes an api.Add/Mul/Sub call
            // - Common subexpressions are cached to avoid redundant computation
            // - The circuit struct contains all witness fields
            // - The Define() method contains all constraint logic
            println!("\n=== Generating Gnark Circuit ===");
            let circuit_code =
                gnark_codegen::generate_circuit_from_bundle(&bundle, "JoltStagesCircuit");

            let circuit_path = output_dir.join("stages_circuit.go");
            std::fs::write(&circuit_path, &circuit_code)
                .unwrap_or_else(|e| panic!("Failed to write circuit file {circuit_path:?}: {e}"));
            println!("  Circuit written to: {circuit_path:?}");
            println!("  Circuit size: {} bytes", circuit_code.len());

            // Get witness values captured during symbolization.
            // VarAllocator records both symbolic variables AND concrete values in a single pass,
            // making mismatch bugs structurally impossible.
            println!("\n=== Generating Witness Data ===");
            let witness_values = var_alloc.witness_values();

            let mut witness_map: HashMap<String, String> = HashMap::new();
            for (idx, name, _target_field) in var_alloc.descriptions_with_fields() {
                let sanitized = gnark_codegen::sanitize_go_name(name);
                if let Some(value) = witness_values.get(&(*idx as usize)) {
                    witness_map.insert(sanitized, value.clone());
                }
            }

            let witness_json =
                serde_json::to_string_pretty(&witness_map).expect("Failed to serialize witness");
            let witness_path = output_dir.join("stages_witness.json");
            std::fs::write(&witness_path, &witness_json)
                .unwrap_or_else(|e| panic!("Failed to write witness file {witness_path:?}: {e}"));
            println!("  Witness written to: {witness_path:?}");
            println!("  Witness variables: {}", witness_map.len());

            println!("\n=== SUCCESS ===");
            println!(
                "Stages 1-7 transpiled to Gnark. Run 'go test' in {:?} to verify.",
                output_dir
            );
        }
        TranspilationTarget::AstBundle => {
            println!("\n=== SUCCESS ===");
            println!("AstBundle written to: {bundle_path:?}");
            println!("  Inputs: {}", bundle.inputs.len());
            println!("  Constraints: {}", bundle.constraints.len());
        }
    }
}
